"""add_whatsapp_instagram_secretaria

Revision ID: bdd75302ef9a
Revises: f48b35110512
Create Date: 2026-05-17 12:19:41.051870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd75302ef9a'
down_revision: Union[str, None] = 'f48b35110512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('denuncias', sa.Column('whatsapp_enviado', sa.Boolean(), nullable=True))
    op.add_column('denuncias', sa.Column('instagram_marcado', sa.Boolean(), nullable=True))
    op.add_column('denuncias', sa.Column('secretaria_slug', sa.String(length=50), nullable=True))
    op.add_column('denuncias', sa.Column('vereador_whatsapp', sa.String(length=50), nullable=True))
    op.add_column('vereadores', sa.Column('whatsapp_gabinete', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vereadores', 'whatsapp_gabinete')
    op.drop_column('denuncias', 'vereador_whatsapp')
    op.drop_column('denuncias', 'secretaria_slug')
    op.drop_column('denuncias', 'instagram_marcado')
    op.drop_column('denuncias', 'whatsapp_enviado')
    # ### end Alembic commands ###
