"""initial_schema

Revision ID: f48b35110512
Revises: 
Create Date: 2026-05-15 12:59:17.018601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f48b35110512'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('denuncias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocolo', sa.String(length=20), nullable=False),
    sa.Column('telegram_user_id', sa.String(length=50), nullable=False),
    sa.Column('telegram_username', sa.String(length=100), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('tipo_midia', sa.String(length=20), nullable=True),
    sa.Column('arquivo_path', sa.String(length=500), nullable=True),
    sa.Column('midia_hash', sa.String(length=64), nullable=True),
    sa.Column('transcricao_audio', sa.Text(), nullable=True),
    sa.Column('descricao_usuario', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('endereco', sa.String(length=500), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('regional', sa.String(length=100), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('valida', sa.Boolean(), nullable=True),
    sa.Column('motivo_invalidade', sa.Text(), nullable=True),
    sa.Column('vereador_nome', sa.String(length=200), nullable=True),
    sa.Column('vereador_email', sa.String(length=200), nullable=True),
    sa.Column('vereador_instagram', sa.String(length=100), nullable=True),
    sa.Column('vereador_twitter', sa.String(length=100), nullable=True),
    sa.Column('secretaria_nome', sa.String(length=200), nullable=True),
    sa.Column('secretaria_email', sa.String(length=200), nullable=True),
    sa.Column('texto_post_sugerido', sa.Text(), nullable=True),
    sa.Column('minuta_email', sa.Text(), nullable=True),
    sa.Column('denuncia_anterior_protocolo', sa.String(length=20), nullable=True),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('grupo_seq', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('moderador_notas', sa.Text(), nullable=True),
    sa.Column('aprovada_em', sa.DateTime(), nullable=True),
    sa.Column('publicada_em', sa.DateTime(), nullable=True),
    sa.Column('link_post', sa.String(length=500), nullable=True),
    sa.Column('email_enviado_em', sa.DateTime(), nullable=True),
    sa.Column('email_enviado', sa.Boolean(), nullable=True),
    sa.Column('telegram_notificado', sa.Boolean(), nullable=True),
    sa.Column('resposta_vereador', sa.Text(), nullable=True),
    sa.Column('resposta_em', sa.DateTime(), nullable=True),
    sa.Column('resolvida_em', sa.DateTime(), nullable=True),
    sa.Column('classificacao_scorecard', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['denuncias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('protocolo')
    )
    op.create_table('vereadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('partido', sa.String(length=50), nullable=True),
    sa.Column('email_gabinete', sa.String(length=200), nullable=True),
    sa.Column('instagram', sa.String(length=100), nullable=True),
    sa.Column('twitter', sa.String(length=100), nullable=True),
    sa.Column('bairros_base', sa.Text(), nullable=True),
    sa.Column('votos_totais_2024', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('followups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denuncia_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('publicado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['denuncia_id'], ['denuncias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followups')
    op.drop_table('vereadores')
    op.drop_table('denuncias')
    # ### end Alembic commands ###
